name: Testing workflow

on: push

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Run black"
        run: pip install black
        run: black --check .
        # Test if we get an error message..

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Run unittest"
        # run: python -m pytest
        run: coverage run pytest
